### ISSUE TITLE
Distant Terrain: add Mod Message callback before disabling terrain

### ISSUE THREAD

**Issue by KABoissonneault** [Nystul-the-Magician/dfunity-mods#8]
As part of the terrain transition ring of Distant Terrain, certain terrain objects are disabled rather than destroyed so they can be reused later, most likely at another location in the world.

This is fine when terrain consists only of DFU's `DaggerfallTerrain` and `DaggerfallBillboardBatch`, but other mods may add other dynamic objects as children to the terrain object, which can interfere once the terrain is reused. Pooling is an optimization, but optimizations have to preserve the "expected behavior" of other mods, which is that terrains are destroyed and not reused once the player leaves the area.

To allow mods to provide Distant Terrain compatibility, I suggest you add an "event" before disabling the terrain in `DistantTerrain.GenerateTerrainTransitionRing`, possible through DFU's mod messaging API.

https://github.com/Nystul-the-Magician/dfunity-mods/blob/fc58546c3eae964babfdfeea51e97a47ba57cdce/DistantTerrain/Scripts/DistantTerrain.cs#L1933

From another mod's perspective, this could look like:
```
void Start()
{
   ...
   ModManager.Instance.SendModMessage("Distant Terrain", "RegisterOnTerrainUnload", OnTerrainUnload);
   ...
}

void OnTerrainUnload(DaggerfallTerrain daggerTerrain)
{
  // Cleanup mod-specific objects under terrain
  ...
}
```

I'm open to other suggestions. The best I've got is adding a component to the terrain and adding a `OnDisable` Unity event, but this would trigger in cases where a terrain is disabled for reasons other than pooling.

I can also provide a PR if you prefer.

**Comment by Nystul-the-Magician** [comment]
I can give it a try, but not 100% sure how to implement it correctly (never used DFU's mod messaging API, only familiar with c# events/delegates), a PR would be highly appreciated ;)

**Comment by KABoissonneault** [comment]
> The best I've got is adding a component to the terrain and adding a OnDisable Unity event, but this would trigger in cases where a terrain is disabled for reasons other than pooling.

We decided to stick with this workaround for now. Seems to be doing fine so far. If we end up needing something fancier, I'll open up with a PR next time
